version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:1.0.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe-script-worker
    image: ghcr.io/camunda-community-hub/zeebe-script-worker:1.0.0
    environment:
      - zeebe.client.broker.contactPoint=b5161a28-2fd3-4879-a99e-60f7478ad3d5.bru-2.zeebe.camunda.io:443
      - zeebe.client.cloud.cluster-id=b5161a28-2fd3-4879-a99e-60f7478ad3d5
      - zeebe.client.cloud.client-id=wROQIC_haG_T6932iWZYsFxwuSIbR~UG
      - zeebe.client.cloud.client-secret=UD5aifgUg9RXJ00.Dy3sIKGG2Qj1lqPJD7-P~Oj5CgysuSjYF.XS1scmEh_Kr2Tg
      - zeebe.client.cloud.region=bru-2
    depends_on:
      - zeebe
    networks:
      - zeebe_network